version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "454953018734"
    AWS_REGION: "ap-northeast-1"
    ECR_REPO_NAME: "abap-mcp"

phases:
  install:
    commands:
      - echo Installing Git LFS...
      - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
      - yum install -y git-lfs
      - git lfs install

  pre_build:
    commands:
      - export ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME"
      - echo Logging in to ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
      - echo Fetching LFS files...
      - git lfs pull
      - ls -la *.tar
      - echo Loading ABAP Accelerator image...
      - docker load -i abap-accelerator-q-3.2.1-node22.tar
      - docker images

  build:
    commands:
      - export ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME"
      - echo Building combined image...
      - ls -la Dockerfile entrypoint.sh
      - docker build -t $ECR_REPO:latest .
      - docker tag $ECR_REPO:latest $ECR_REPO:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - export ECR_REPO="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME"
      - echo Pushing to ECR...
      - docker push $ECR_REPO:latest
      - docker push $ECR_REPO:$CODEBUILD_BUILD_NUMBER
      - echo "Build complete"