AWSTemplateFormatVersion: 2010-09-09
Description: ABAP Accelerator MCP Server - Complete Stack with CodeBuild

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC with VPN connectivity to SAP system
  
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnets with route to SAP system via VPN
  
  GitHubRepo:
    Type: String
    Description: GitHub repository URL (HTTPS)
    Default: "https://github.com/ET-n-pan/abap-mcp.git"
  
  GitHubBranch:
    Type: String
    Default: main
  
  SapHost:
    Type: String
    Default: "10.1.1.122:8000"
    Description: SAP host and port (no http:// prefix)
  
  SapClient:
    Type: String
    Default: "310"
  
  SapUsername:
    Type: String
    Default: "101674115"
  
  SapLanguage:
    Type: String
    Default: "JA"
  
  SapSecure:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]

  # Set to 0 for initial deployment, then update to 1 after image is built
  DesiredCount:
    Type: Number
    Default: 0
    Description: Set to 0 initially, update to 1 after CodeBuild completes

Resources:
  # ECR Repository
  EcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: abap-mcp
      ImageScanningConfiguration:
        ScanOnPush: true


  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: abap-mcp-codebuild-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                Resource: !GetAtt EcrRepository.Arn
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: "*"

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: abap-mcp-build
      Description: Build ABAP Accelerator MCP Docker image
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        PrivilegedMode: true  # Required for Docker
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_REGION
            Value: !Ref AWS::Region
          - Name: ECR_REPO_NAME
            Value: abap-mcp
      Source:
        Type: GITHUB
        Location: !Ref GitHubRepo
        BuildSpec: buildspec.yml
        GitCloneDepth: 1
      SourceVersion: !Ref GitHubBranch
      TimeoutInMinutes: 30

  # Secrets Manager
  SapPasswordSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: abap-mcp/sap-password
      Description: SAP password for ABAP Accelerator MCP
      SecretString: "REPLACE_ME_AFTER_DEPLOYMENT"
      KmsKeyId: alias/aws/secretsmanager
  # ECS Cluster
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: abap-mcp-cluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: abap-mcp-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref SapPasswordSecret

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: abap-mcp-task-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SSMForExecCommand
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Resource: "*"

  TaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: abap-mcp-sg
      GroupDescription: Security group for ABAP MCP Fargate task
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 10.0.0.0/8
          Description: MCP HTTP access from VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 10.0.0.0/8
          Description: SAP HTTP access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS outbound (ECR, Secrets Manager)

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/abap-mcp
      RetentionInDays: 7

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: EcrRepository
    Properties:
      Family: abap-mcp
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '512'
      Memory: '1024'
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: abap-mcp
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/abap-mcp:latest
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: SAP_HOST
              Value: !Ref SapHost
            - Name: SAP_CLIENT
              Value: !Ref SapClient
            - Name: SAP_USERNAME
              Value: !Ref SapUsername
            - Name: SAP_LANGUAGE
              Value: !Ref SapLanguage
            - Name: SAP_SECURE
              Value: !Ref SapSecure
          Secrets:
            - Name: SAP_PASSWORD
              ValueFrom: !Ref SapPasswordSecret
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: abap-mcp

  # ECS Service
  EcsService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: abap-mcp-service
      Cluster: !Ref EcsCluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED  # For testing - change to DISABLED with NAT for prod
          Subnets: !Ref PrivateSubnetIds
          SecurityGroups:
            - !Ref TaskSecurityGroup
      EnableExecuteCommand: true

Outputs:
  EcrRepository:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/abap-mcp
    Description: ECR repository URI
  
  CodeBuildProject:
    Value: !Ref CodeBuildProject
    Description: CodeBuild project name - trigger this first
  
  ClusterName:
    Value: !Ref EcsCluster
  
  ServiceName:
    Value: !GetAtt EcsService.Name
  
  SecretArn:
    Value: !Ref SapPasswordSecret
    Description: Update this secret with actual SAP password
  
  LogGroup:
    Value: !Ref LogGroup
